### ISSUE TITLE
Favicon bug

### ISSUE THREAD

**Issue by nethanel-ctrl** [jonathancaleb/enoflow#6]
Describe the bug
The favicon has been updated locally but the change is not reflected in the Vercel production environment. The old favicon still persists on the production site.

To Reproduce

Go to the production site hosted on Vercel.
Inspect the browser tab to view the favicon.
Compare it with the favicon on the local environment.
Notice that the production site still shows the old favicon.
Expected behavior
The favicon should update in the Vercel production environment to match the changes made locally.

Screenshots
![Screenshot 2024-06-13 122505](https://github.com/jonathancaleb/enoflow/assets/172575265/f91a216b-74d5-4318-8221-51f83321fb07)

Screenshot of the local environment with the updated favicon.
Screenshot of the Vercel production environment with the old favicon.
Additional context

The favicon file was updated and verified locally.
Cleared browser cache and deployed changes multiple times on Vercel without success.
Other changes deployed to Vercel are reflected correctly, except for the favicon.

**Comment by jonathancaleb** [comment]
this issue has been fixed in the latest commit
